version: "3.3"
services:
  recommender-app:
    image: eveestudio/recommender:0.3.0-alpine
    networks:
      - traefik-public
      - database
    environment:
      - DB_HOST=database
    ports:
      - 8000:8000
  database:
    image: postgres:16.3
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - database
networks:
  database: